### ISSUE TITLE
errors when run scraper.py

### ISSUE THREAD

**Issue by 2705714131** [AbirHasan2005/TelegramScraper#21]
[+] Enter a Number: 31
[+] Fetching Members ...
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/TelegramScraper/scraper.py", line 85, in <module>
    all_participants = client.get_participants(target_group, aggressive=True)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/data/data/com.termux/files/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/chats.py", line 507, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/requestiter.py", line 113, in collect
    async for message in self:
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/chats.py", line 222, in _load_next_chunk
    results = await self.client(self.requests)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/users.py", line 80, in _call
    raise MultiError(exceptions, results, requests)
telethon.errors.common.MultiError: ([None, FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)')], [<telethon.tl.types.channels.ChannelParticipants object at 0x7b59543310>, None, None, None, <telethon.tl.types.channels.ChannelParticipants object at 0x7b597bf8b0>, None, None, <telethon.tl.types.channels.ChannelParticipants object at 0x7b5969a7a0>, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae4910>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae49d0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae4a90>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae4b50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae4c10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae4cd0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae4d90>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae4e50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae4f10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae4fd0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae5090>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae5150>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae5210>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae52d0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae5390>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae5450>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae5510>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae55d0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae5690>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae5750>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae5810>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae58d0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae5990>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae5a50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae5b10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7b59ae5bd0>])

**Comment by pmrksof** [comment]
i'm getting same error, Maybe it's API problem

**Comment by jakbin** [comment]
remove `aggressive=True` from `scraper.py` because telethon have removed this argument.
