### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SlaSerX** [AbirHasan2005/TelegramScraper#28]
Traceback (most recent call last):
  File "adder.py", line 104, in <module>
    client(InviteToChannelRequest(target_group_entity, [user_to_add]))
  File "/home/slaserx/.local/lib/python3.8/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/slaserx/.local/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/slaserx/.local/lib/python3.8/site-packages/telethon/client/users.py", line 52, in _call
    raise errors.FloodWaitError(request=r, capture=diff)
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 38666 seconds is required (caused by InviteToChannelRequest)
Unexpected Error!

**Comment by worldsmoker** [comment]
same problem here also...

**Comment by fredlegrand111** [comment]
same problem here also...

**Comment by jakbin** [comment]
telegram api has a limit. try script next day.
