### ISSUE TITLE
My script keeps ending and sometimes get these codes

### ISSUE THREAD

**Issue by Westsideff** [AbirHasan2005/TelegramScraper#34]
Adding 1613426659
Traceback (most recent call last):
  File "/root/TelegramScraper/adder.py", line 99, in <module>
    user_to_add = client.get_input_entity(user['username'])
  File "/usr/local/lib/python3.9/dist-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 437, in get_input_entity
    await self._get_entity_from_string(peer))
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 553, in _get_entity_from_string
    result = await self(
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 52, in _call
    raise errors.FloodWaitError(request=r, capture=diff)
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 24348 seconds is required (caused by ResolveUsernameRequest)
Unexpected Error! 
Adding 354995733
Traceback (most recent call last):
  File "/root/TelegramScraper/adder.py", line 99, in <module>
    user_to_add = client.get_input_entity(user['username'])
  File "/usr/local/lib/python3.9/dist-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 437, in get_input_entity
    await self._get_entity_from_string(peer))
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 553, in _get_entity_from_string
    result = await self(
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 52, in _call
    raise errors.FloodWaitError(request=r, capture=diff)
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 24348 seconds is required (caused by ResolveUsernameRequest)
Unexpected Error!

And 

Traceback (most recent call last):
  File "/root/TelegramScraper/adder.py", line 104, in <module>
    client(InviteToChannelRequest(target_group_entity, [user_to_add]))
  File "/usr/local/lib/python3.9/dist-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 52, in _call
    raise errors.FloodWaitError(request=r, capture=diff)
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 21295 seconds is required (caused by InviteToChannelRequest)
Unexpected Error!

**Comment by Westsideff** [comment]
It ended with this code today 


Traceback (most recent call last):
  File "/root/TelegramScraper/adder.py", line 104, in <module>
    client(InviteToChannelRequest(target_group_entity, [user_to_add]))
  File "/usr/local/lib/python3.9/dist-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 52, in _call
    raise errors.FloodWaitError(request=r, capture=diff)
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 465 seconds is required (caused by InviteToChannelRequest)
Unexpected Error! 
Adding 1199886044
Traceback (most recent call last):
  File "/root/TelegramScraper/adder.py", line 104, in <module>
    client(InviteToChannelRequest(target_group_entity, [user_to_add]))
  File "/usr/local/lib/python3.9/dist-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 52, in _call
    raise errors.FloodWaitError(request=r, capture=diff)
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 465 seconds is required (caused by InviteToChannelRequest)
Unexpected Error!

**Comment by fluential** [comment]
The owner has to implement correct FloodWait exception handling via here https://stackoverflow.com/questions/57529546/how-to-handle-flood-wait-errors-when-using-telethon-sync
