### ISSUE TITLE
How to unlock database?

### ISSUE THREAD

**Issue by uruk-hai-21** [AbirHasan2005/TelegramScraper#6]
Traceback (most recent call last):
  File "adder.py", line 36, in <module>
    with client:
  File "/usr/local/lib/python3.8/dist-packages/telethon/helpers.py", line 184, in _sync_enter
    return loop.run_until_complete(self.__aenter__())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/auth.py", line 713, in __aenter__
    return await self.start()
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/auth.py", line 140, in _start
    await self.connect()
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/telegrambaseclient.py", line 524, in connect
    self.session.auth_key = self._sender.auth_key
  File "/usr/local/lib/python3.8/dist-packages/telethon/sessions/sqlite.py", line 180, in auth_key
    self._update_session_table()
  File "/usr/local/lib/python3.8/dist-packages/telethon/sessions/sqlite.py", line 194, in _update_session_table
    c.execute('delete from sessions')
sqlite3.OperationalError: database is locked
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection._send_loop() running at /usr/local/lib/python3.8/dist-packages/telethon/network/connection/connection.py:306> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2a6c062d60>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<Connection._recv_loop() running at /usr/local/lib/python3.8/dist-packages/telethon/network/connection/connection.py:324> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2a6c062eb0>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<MTProtoSender._send_loop() running at /usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py:460> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2a6c08a070>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<MTProtoSender._recv_loop() running at /usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py:503> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2a6c08a0a0>()]>>

**Comment by AbirHasan2005** [comment]
Delete Client Session Files!

**Comment by uruk-hai-21** [comment]
Hi Abir, thank you for your reply!
Do you mean /TelegramScraper/+123456789.session file?

**Comment by AbirHasan2005** [comment]
> Hi Abir, thank you for your reply!
> Do you mean /TelegramScraper/+123456789.session file?

Yes Sir
